# src/main/resources/application-local.yml

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    activate:
      on-profile: local  # ✅ Correct way in Spring Boot 2.4+


  datasource:
    url: jdbc:mysql://host.docker.internal:3306/Userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gofar.1315@gmail.com
    password: ixzdigerbsrtbenq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
